[package]
name = "todo_library"
version = "0.1.0"
edition = "2021"

[lib]
name = "todo_library"
path = "src/lib.rs"


[dependencies]
chrono = { version = "0.4.33", features = ["serde"] }
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = "0.15.7"
